//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see http://www.gnu.org/licenses/.
// 

//
// TODO generated message class
//
packet RelayDENMs {
    double relayedBrakingTime = 0;
    double relayedCurrentSimTime = 0;
    double relayedDecelarationRate = 0;
    double relayedSpeedOfLeader = 0;
    int relayedIdOfVehicle = 0;
    int relayedSeqNumber = 0;
    double relayedPredictedDelayOfLastVeh = 0;
    double relayedSBAvgWaitTime = 0;
}
